pr:
  - master
  - releases/*

jobs:
- template: run-tests.yml
  parameters:
    name: Py310_Ubuntu
    vmImage: 'ubuntu-latest'
    pythonVersion: '3.10'
- template: run-tests.yml
  parameters:
    name: Py310_Mac
    vmImage: 'macOS-latest'
    pythonVersion: '3.10'
- template: run-tests.yml
  parameters:
    name: Py310_Win
    vmImage: 'windows-latest'
    pythonVersion: '3.10'
- template: run-tests.yml
  parameters:
    name: Py39_Ubuntu
    vmImage: 'ubuntu-latest'
    pythonVersion: '3.9'
- template: run-tests.yml
  parameters:
    name: Py39_Mac
    vmImage: 'macOS-latest'
    pythonVersion: '3.9'
- template: run-tests.yml
  parameters:
    name: Py39_Win
    vmImage: 'windows-latest'
    pythonVersion: '3.9'
- template: run-tests.yml
  parameters:
    name: Py38_Ubuntu
    vmImage: 'ubuntu-latest'
    pythonVersion: '3.8'
- template: run-tests.yml
  parameters:
    name: Py38_Mac
    vmImage: 'macOS-latest'
    pythonVersion: '3.8'
- template: run-tests.yml
  parameters:
    name: Py38_Win
    vmImage: 'windows-latest'
    pythonVersion: '3.8'
